[package]
name = "tomlq"
version = "0.2.2"
authors = [
  "Natalia Maximo <iam@natalia.dev>",
  "James Munns <james.munns@gmail.com>",
]
edition = "2021"
license = "MIT"
repository = "https://github.com/cryptaliagy/tomlq"
description = "A tool for obtaining information from a TOML file on the command line"

[package.metadata.binstall]
pkg-fmt = "tgz"

[package.metadata.binstall.overrides.x86_64-unknown-linux-gnu]
pkg-url = "{ repo }/releases/download/{ version }/{ name }.amd64{ archive-suffix }"

[package.metadata.binstall.overrides.aarch64-unknown-linux-gnu]
pkg-url = "{ repo }/releases/download/{ version }/{ name }.arm64{ archive-suffix }"

[package.metadata.binstall.overrides.armv7-unknown-linux-gnueabi]
pkg-url = "{ repo }/releases/download/{ version }/{ name }.armv7{ archive-suffix }"

[package.metadata.binstall.overrides.armv7-unknown-linux-gnueabihf]
pkg-url = "{ repo }/releases/download/{ version }/{ name }.armv7hf{ archive-suffix }"

[package.metadata.binstall.overrides.x86_64-unknown-linux-musl]
pkg-url = "{ repo }/releases/download/{ version }/{ name }.amd64{ archive-suffix }"

[package.metadata.binstall.overrides.aarch64-unknown-linux-musl]
pkg-url = "{ repo }/releases/download/{ version }/{ name }.arm64{ archive-suffix }"

[package.metadata.binstall.overrides.armv7-unknown-linux-musleabi]
pkg-url = "{ repo }/releases/download/{ version }/{ name }.armv7{ archive-suffix }"

[package.metadata.binstall.overrides.armv7-unknown-linux-musleabihf]
pkg-url = "{ repo }/releases/download/{ version }/{ name }.armv7hf{ archive-suffix }"

[package.metadata.binstall.overrides.aarch64-apple-darwin]
pkg-url = "{ repo }/releases/download/{ version }/{ name }.darwin-arm64{ archive-suffix }"

[package.metadata.binstall.overrides.x86_64-apple-darwin]
pkg-url = "{ repo }/releases/download/{ version }/{ name }.darwin-amd64{ archive-suffix }"

[lib]
doc = true
doctest = true
name = "tq"
test = true

[[bin]]
name = "tq"
required-features = ["bin"]
test = false

[dependencies]
anyhow = { version = "1.0.95", features = ["backtrace"], optional = true }
bat = { version = "0.25.0", default-features = false, features = [
  "build-assets",
  "regex-fancy",
], optional = true }
clap = { version = "4.5", features = [
  "derive",
  "help",
  "usage",
], optional = true }
colored = { version = "3.0.0", optional = true }
console = { version = "0.15.10", features = [
  "windows-console-colors",
], optional = true }
serde = "1.0.217"
thiserror = "2.0.11"
toml = "0.8"

[dependencies.serde_json]
version = "1.0.135"
features = ["indexmap", "preserve_order", "raw_value", "unbounded_depth"]
optional = true

[features]
default = ["bin", "json"]
bin = ["dep:anyhow", "dep:clap"]
# THIS FEATURE IS FOR THE PREVIOUS VERSION OF TOMLQ AND IS NOT USED BY THE TQ BINARY.
# IT WILL BE REMOVED IN A FUTURE RELEASE.
color = ["dep:colored"]
json = ["dep:serde_json"]
# Syntax highlighting feature for the tq CLI -- optional, disabled by default.
syntax-highlighting = ["bin", "dep:bat", "dep:console"]

[profile.release]
opt-level = "z"
strip = true
lto = true
